config/routes.rb
Rails.application.routes.draw do
  
  root to: "public#homepage"
  devise_for :accounts
  get '/dashboard', to: 'accounts#index'
  get '/profile/:username', to: 'accounts#show', as: :profile
  get 'post/like/:post_id', to: 'likes#create', as: :like_post
  post 'follow/account', to: 'accounts#follow_account', as: :follow_account
  resources :posts, only: [:new, :create, :show]

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes

  mount_uploader :image, ImageUploader

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    0
  end

  def total_following
    0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :account
  
  validates :account_id, uniqueness: { scope: :post_id }
  
  after_create :increment_post_like_counter
  after_destroy :decrement_post_like_counter

  private

  def increment_post_like_counter
    Post.find(post_id).increment(:total_likes_count).save
  end

  def decrement_post_like_counter
    Post.find(post_id).decrement(:total_likes_count).save
  end

end

app/models/post.rb
class Post < ApplicationRecord
  default_scope { order created_at: :desc }
  scope :active, -> { where(active: true) }

  mount_uploader :image, ImageUploader
  
  belongs_to :account
  has_many :likes
  
  def total_likes
    0
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!

  def index
    @posts = Post.active
    @follower_suggestions = Account.where.not(id: current_account.id)
  end

  def show
    @account = Account.find_by_username(params[:username])
  end

  def follow_account
    account_id = params[:follow_account]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password, :image, :description, :website])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :email, :password, :image, :description, :website])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_account!

  def create
    @like = current_account.likes.build()
    @like.post_id = params[:post_id]
    @post_id = params[:post_id]
    existing_like = Like.where(post_id: params[:post_id], account_id: current_account.id)
    respond_to do |format|
      format.js {
        if existing_like.any?
          @success = false
          existing_like.first.destroy
        elsif @like.save
          @success = true
        else
          @success = false
        end
        @post_likes = Post.find(@post_id).total_likes_count
        render "like"
      }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!

  def new
    @post = Post.new
  end

  def create
    @post = current_account.posts.build(post_params)
    if @post.save
      redirect_to dashboard_path, notice: "Post created successfully"
    else
      render 'new', notice: "Unable to create post"
    end
  end

  def show
  end

  private

    def post_params
      params.require(:post).permit(:description, :image, :image_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def homepage
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def profile_picture(account, width = 100)
    image_path = account.image.present? ? account.image.thumb.url : "placeholder-profile.jpg"
    image_tag(image_path, width: width, class: "img-circle")
  end

  def can_edit_profile? profile_id
    account_signed_in? && current_account.id == profile_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_liked_by_user? post_id
    Like.where(post_id: post_id, account_id: current_account.id).any?
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |user| %>
  <div class="recommended-follower">
    <div class="row">
      <div class="col-2">
        <%= link_to profile_picture(user, 40), profile_path(user.username) %>
      </div>
      <div class="col-10">
        <%= form_tag follow_account_path, method: :post, class: "float-right", do %>
          <%= hidden_tag :follow_id %>
          <%= submit_tag "Follow", class: "btn btn-info" %>
        <%end%>
        <%= link_to user.username, profile_path(user.username), class: "text-dark" %>
        <p class="text-muted"><%= user.created_at > 2.day.ago ? "New to Instagram" : "Followed by X users"%></p>
      </div>
    </div>
  </div>
<%end%>

app/views/accounts/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8'>
      <% @posts.each do |post| %>
        <div class='insta-post'>
          
          <div class='post-meta'>
            <%= link_to image_tag(current_account.image.thumb.url, class: "img-circle"), profile_path(post.account.username) %>
            <%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %>
          </div>
          
          <%= image_tag post.image.url, class: 'img img-fluid' %>
          
          <div class="post-details">
            <div class="post-actions">
              <i class="fa fa-heart fa-2x post-like like-<%= post.id %> <%= "active" if post_liked_by_user?(post.id) %>" data-id="<%= post.id %>"></i>
              <i class="fa fa-comment fa-2x post-comment"></i>
            </div>

            <p><strong id="post-<%= post.id %>-likes"><%= post.total_likes_count %> likes</strong></p>
            <p><strong id="post-<%= post.id %>-comments"><%= link_to post.account.username, profile_path(post.account.username), class: "text-dark" %></strong></p>
            <%= simple_format post.description %>
            <p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p>
          </div>
        </div>
      <%end%>
    </div>
    <div class='col-4'>
      <div class='account-summary'>
        <p>
          <%= link_to image_tag(current_account.image.thumb.url, class: "img-circle"), profile_path(current_account.username) %>
          <strong><%= current_account.username %></strong><br>
        </p>
        <p>
          <%= current_account.full_name %>
        </p>
      </div>
      <div class="follower-suggestions">
        <%= link_to "View All", "#", class: "float-right text-dark" %>
        <p class="text-muted">Suggestions for you</p>
        <%= render "follower_suggestions" %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= profile_picture @account, 200 %>
    </div>
    <div class="col-8 text-left">
      <h1><%= @account.full_name %></h1>
      <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-secondary" if can_edit_profile? @account.id %>
      
      <div>
        <div class="row profile-stats">
          <div class="col-4">
            <%= @account.posts.count %> posts
          </div>
          <div class="col-4">
            <div class="profile-stats"><%= @account.total_followers %> followers</div>
          </div>
          <div class="col-4">
            <div class="profile-stats"><%= @account.total_following %> following</div>
          </div>
        </div>
      </div>
    
      <p><%= @account.full_name %></p>
      <p><%= simple_format @account.description %></p>
      <p><%= link_to @account.website, @account.website if @account.website.present? %></p>
    </div>
  </div>
  <div class="row profile-posts">
    <% @account.posts.each do |post| %>
      <div class="col-4">
        <div class="insta-post">
          <%= image_tag post.image.url %>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/_navbar_content.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="/">Instagram Clone</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if account_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
          </li>
        <%else%>
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c2fbed3a27.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar_content' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <% unless flash.empty? %>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          <%end%>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/likes/like.js.erb
<% if @success == true %>
  $(".like-<%= @post_id %>").addClass("active");
<% else %>
  $(".like-<%= @post_id %>").removeClass("active");
<%end%>
$("#post-<%= @post_id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control"%>
  </div>
  <%= f.submit "Save Post", class: "btn btn-success" %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>